name = "anjiachen-bot"
main = "worker.js"
compatibility_date = "2026-09-06"

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "KV"
id = "dcab5407f1c44853814dbdfceb233ad8"

[vars]
OKX_MODE = "demo"
TELEGRAM_CHAT_ID = "5326483009"